events {}

http{
    server{
        listen 80;

        location / {
            proxy_pass http://frontend:80;
            proxy_set_header Host $host; b
        }

        location /api/ {
            proxy_pass http://backend-api:8000/;
        }
    }
}