  apiVersion: apps/v1     
  kind: Deployment
  metadata:                                                                     
    name: notification-service
  spec:                                                                         
    replicas: 1   
    selector:                                                                   
      matchLabels:
        app: notification-service                                               
    template:     
      metadata:
        labels:
          app: notification-service
      spec:
        containers:
          - name: notification-service
            image: aq150/notification-service:latest
            env:                                                                
              - name: DATABASE_URL
                valueFrom:                                                      
                  secretKeyRef:
                    name: app-secrets
                    key: DATABASE_URL
              - name: RABBITMQ_URL
                valueFrom:                                                      
                  secretKeyRef:
                    name: app-secrets                                           
                    key: RABBITMQ_URL
              - name: SENDGRID_API_KEY
                valueFrom:
                  secretKeyRef:                                                 
                    name: app-secrets
                    key: SENDGRID_API_KEY                                       
              - name: SENDGRID_FROM_EMAIL
                valueFrom:
                  secretKeyRef:
                    name: app-secrets
                    key: SENDGRID_FROM_EMAIL
                                                                                
---
apiVersion: v1                                                                
kind: Service   
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - port: 3000
      targetPort: 3000